### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/jet-sms#9]
Hi @erdemkeren 

Are you still interested in maintain this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by erdemkeren** [comment]
Hello @atymic!

Sure. I will.

**Comment by atymic** [comment]
Thanks mate 😄

**Comment by atymic** [comment]
I can make a PR if you would like?

**Comment by erdemkeren** [comment]
Done.

**Comment by atymic** [comment]
Thanks :)
